server:
  port: 8085
mybatis:
  type-aliases-package: com.zpark.pojo
  mapper-locations:
  - classpath:mapper/*.xml
spring:
  application:
    name: springcloud-dept-provider
#  #    关闭热部署
#  devtools:
#    restart:
#      enabled : false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gmduser
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
#将服务提供者注册到eureka注册中心中去
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01:8761/eureka,http://eureka02:8762/eureka,http://eureka03:8763/eureka
    #是否将自己这个服务注册到EurekaServer中  默认True 此服务为Server  所以为False
    register-with-eureka: true
    #是否从EurekaServer获取注册信息 默认True 单点ES不存在其他的EurkaServer 所以为False
    fetch-registry: true

